version: "3.8"

services:
  mongo:
    container_name: slim_mongo
    image: mongo:5
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./db-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${STPLAPP_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${STPLAPP_MONGO_PWD}

  mongo-express:
    container_name: slim_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${STPLAPP_MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${STPLAPP_MONGO_PWD}
      ME_CONFIG_MONGODB_URL: mongodb://${STPLAPP_MONGO_USER}:${STPLAPP_MONGO_PWD}@${STPLAPP_MONGO_HOST}:${STPLAPP_MONGO_PORT}/
    depends_on:
      - mongo

  php:
    container_name: slim_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/slim_app
    environment: 
      - VEHICLE_API_URL=${VEHICLE_API_URL}
      - VEHICLE_API_CLIENT_ID=${VEHICLE_API_CLIENT_ID}
      - VEHICLE_API_TOKEN=${VEHICLE_API_TOKEN}
      - STPLAPP_MONGO_HOST=${STPLAPP_MONGO_HOST}
      - STPLAPP_MONGO_USER=${STPLAPP_MONGO_USER}
      - STPLAPP_MONGO_PWD=${STPLAPP_MONGO_PWD}
      - STPLAPP_MONGO_PORT=${STPLAPP_MONGO_PORT}
    depends_on:
      - mongo

  nginx:
    container_name: slim_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/slim_app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php